#if defined _smsshop_const_included
	#endinput
#endif
#define _smsshop_const_included

#pragma library "smsshop_const"

#define VERSION "1.0.0"
#define AUTHOR "SklepSMS"

#define PREFIX "SklepSMS"

#define MAX_SERVICE_ID		15
#define MAX_SERVICE_FLAGS	25

enum
{
	VALUE_1_23 = 1,
	VALUE_2_46,
	VALUE_3_69,
	VALUE_4_92,
	VALUE_6_15,
	VALUE_7_38,
	VALUE_11_07,
	VALUE_17_22,
	VALUE_23_37,
	VALUE_30_75
}
