let Config = {
    build: false,
    baseURL: null,
    style: 1,
    user_id: null,
    username: null,
    email: null,
    network: {
        owner: false,
        ownerName: null,
        net_id: 0,
        web_page: null,
        date: null,
        license: true,
        license_update: null,
        license_expire: null,
        trial: 1,
        balance: 0.0
    },
    shop: {
        version: '1.0.0',
        amxx: {
            v182: {
                pack: 'sklepsms-182-v1_0.rar',
                update: 'sklepsms-182-v1_0u.rar'
            },
            v183: {
                pack: 'sklepsms-183-v1_0.rar',
                update: 'sklepsms-183-v1_0u.rar'
            },
            v19: {
                pack: 'sklepsms-19-v1_0.rar',
                update: 'sklepsms-19-v1_0u.rar'
            }
        },
        networks: 0,
        servers: 0,
        services: 0,
        buy: 0,
        income: 0
    },
    prices: [
        { id: 1, value: "1.23" },
        { id: 2, value: "2.46" },
        { id: 3, value: "3.69" },
        { id: 4, value: "4.92" },
        { id: 5, value: "6.15" },
        { id: 6, value: "7.38" },
        { id: 7, value: "11.07" },
        { id: 8, value: "17.22" },
        { id: 9, value: "23.37" },
        { id: 10, value: "30.75" },
    ],
    colors: [
        '#ff6384',
        '#36a2eb',
        '#ffce56',
        '#d11141',
        '#00b159',
        '#00aedb',
        '#f37735',
        '#ffc425',
        '#d9534f',
        '#5bc0de',
        '#5cb85c',
        '#428bca',
        '#a200ff',
        '#f47835',
        '#d41243',
        '#8ec127',
        '#966842',
        '#f44747',
        '#eedc31',
        '#7fdb6a',
        '#0e68ce',
        '#326ada',
        '#433e90',
        '#00aba9',
        '#ff0097',
        '#1ba1e2',
        '#f09609',
        '#edc951',
        '#eb6841',
        '#cc2a36',
        '#4f372d',
        '#00a0b0'
    ],
    urls: {
        checkPartner: "https://sklepsms.pl/ajax/checkPartnership.php",
        getServerInfo: "https://sklepsms.pl/ajax/getServerInfo.php",
        getAccountReports: "https://sklepsms.pl/ajax/getAccountReports.php",
        getNetworkServices: "https://sklepsms.pl/ajax/getNetworkServices.php",
        addServer: "https://sklepsms.pl/ajax/addServer.php",
        addReport: "https://sklepsms.pl/ajax/addReport.php",
        addAnswer: "https://sklepsms.pl/ajax/addAnswer.php",
        openAnswer: "https://sklepsms.pl/ajax/openAnswer.php",
        closeAnswer: "https://sklepsms.pl/ajax/closeAnswer.php",
        generateDotpay: "https://sklepsms.pl/ajax/generateDotpay.php",
        leaveNetwork: "https://sklepsms.pl/ajax/leaveNetwork.php",
        deleteNetwork: "https://sklepsms.pl/ajax/deleteNetwork.php",
        changeEmail: "https://sklepsms.pl/ajax/changeEmail.php",
        changePassword: "https://sklepsms.pl/ajax/changePassword.php",
        logToDatabase: "https://sklepsms.pl/ajax/logToDatabase.php",
        config: "https://sklepsms.pl/ajax/config.php",
        getPartners: "https://sklepsms.pl/ajax/getPartners.php",
        addPartner: "https://sklepsms.pl/ajax/addPartner.php",
        generateVerifyFile: "https://sklepsms.pl/ajax/generateVerifyFile.php",
        getNetworksNames: "https://sklepsms.pl/ajax/getNetworksNames.php",
        addNetwork: "https://sklepsms.pl/ajax/addNetwork.php",
        getNetworkApis: "https://sklepsms.pl/ajax/getNetworkApis.php",
        addServerService: "https://sklepsms.pl/ajax/addServerService.php",
        getServiceIndexes: "https://sklepsms.pl/ajax/getServiceIndexes.php",
        addService: "https://sklepsms.pl/ajax/addService.php",
        getService: "https://sklepsms.pl/ajax/getService.php",
        editServerService: "https://sklepsms.pl/ajax/editServerService.php",
        editService: "https://sklepsms.pl/ajax/editService.php",
        activeTrial: "https://sklepsms.pl/ajax/activeTrial.php",
        deleteNetworkService: "https://sklepsms.pl/ajax/deleteNetworkService.php",
        addApiAccount: "https://sklepsms.pl/ajax/addApiAccount.php",
        editApiAccount: "https://sklepsms.pl/ajax/editApiAccount.php",
        deleteApiAccount: "https://sklepsms.pl/ajax/deleteApiAccount.php",
        getUpdates: "https://sklepsms.pl/ajax/getUpdates.php",
        getNotifications: "https://sklepsms.pl/ajax/getNotifications.php",
        setNotifiRead: "https://sklepsms.pl/ajax/setNotifiRead.php",
        sendNotification: "https://sklepsms.pl/ajax/sendNotification.php",
        getServerStats: "https://sklepsms.pl/ajax/getServerStats.php",
        deleteServer: "https://sklepsms.pl/ajax/deleteServer.php",
        getIncome: "https://sklepsms.pl/ajax/getIncome.php",
        getServices: "https://sklepsms.pl/ajax/getServices.php",
        deleteService: "https://sklepsms.pl/ajax/deleteService.php",
        serverSettings: "https://sklepsms.pl/ajax/serverSettings.php",
        verifyNetwork: "https://sklepsms.pl/ajax/verifyNetwork.php",
        footerData: "https://sklepsms.pl/ajax/footerData.php",
        addCode: "https://sklepsms.pl/ajax/addCode.php",
        deleteCode: "https://sklepsms.pl/ajax/deleteCode.php",
        getCodes: "https://sklepsms.pl/ajax/getCodes.php",
        sendNews: "https://sklepsms.pl/ajax/sendNews.php"
    }
};

export default Config;
